######################
# Site configuration #
######################

title: GOV.UK Design / Decision History
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a template for the design / decision hisotry cms solution
baseurl: "/mhclg-design-codes" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

##################
# Build settings #
##################

paginate: 5
paginate_path: "/_posts"

sass:
  sass_dir: _sass

######################
# Site header        #
######################
header:
  type: "service-name-with-navigation" # Set to "default", "service-name" or "service-name-with-navigation" to change the header
  site-name: "Design / Decision History" # Appears in the header, regardless of style
  service-name: "Design / Decision History" # Appears in the header, if site.header.type is set to "service-name" or "service-name-with-navigation"
  links:
  # - name: "Page title"
  #   url: "/"
  #   alt: "Go to Page 1"
  # - name: "Page title"
  #   url: "/2/"
  #   alt: "Go to Page 2"


######################
# Site footer        #
######################
footer:
  type: "default" # Set to "default"
  ogl: false # Display (true) or disable (false) the OGL licence text
  crown-copyright: false # Display (true) or disable (false) the Crown copyright text and symbol
  # links:
  # - name: "Item 1"
  #   url: "/"
  #   alt: "Go to Item 1"
  # - name: "Item 2"
  #   url: "/2/"
  #   alt: "Go to Item 2"


######################
# Site sidebar       #
######################
sidebar:
  type: "default" # Set to "default"
  header: "About this site"
  description: "A basic Jekyll theme built on the GOV.UK Design System."

###############
# Collections #
###############
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
        path: "/_posts"
        type: "posts"
    values:
      layout: "post"


plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

plugins: [jekyll-paginate]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
